# Generated by Django 4.1.5 on 2023-02-23 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_features_details_features_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
