phrase = "\'Giraffe Academy\'"
print(phrase + "\tis not animal academy")
print(phrase + "\nis not animal academy")
print(phrase.lower())
print(phrase.upper())
print(phrase.islower())
print(phrase.isupper())
print(phrase.upper().isupper())
print(phrase.lower().islower())
print(len(phrase))
print(phrase[0])
print(phrase[3].upper())
print(phrase.index("\'"))
print(phrase.index("Academy"))
print(phrase.index("m"))
print(phrase.replace("Aca", "Aka"))