lucky_num = [2,4,8,16,32]
friends = ["Amit","Usha","Prashil","Saman","MEE","MEE"]

friends.append("lool")
print(friends)
friends.insert(1, "sus")
print(friends)
friends.remove("Prashil")
print(friends)
friends.pop()
print(friends)
print(friends.index("MEE"))
print(friends)
print(friends.count("MEE"))
print(friends)
friends.sort()
print(friends)
friends.extend(lucky_num)
print(friends)
friends2 = friends.copy()
print(friends2)
friends2.clear()
print(friends2)
