print("Roses are {colour}")
print("{Noun} are blue")
print("I love {celebs}")
colour = input("Enter a colour: ")
noun = input("Enter a noun: ")
celeb = input("Enter a celebrity: ")
print("Roses are " + colour)
print(noun + " are blue")
print("I love " + celeb)
